version: "3.7"  #version 3.7 buna uygun requrementları yazmak gerekli
# database ve app iki service var. 
# flaskda yazan şifre ve usernameler.
#database ismi de flaskdan
# my app  image build ediyourz. depends_on önce database kalksın sonra bu build olsun diyoruz. 
# burada custom bir network tanımladık tanımlamasak da default olurd. 
services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: todo_db
            MYSQL_USER: wayne
            MYSQL_PASSWORD: wayne1
        networks:
            - clarusnet
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - clarusnet

networks:
    clarusnet:
        driver: bridge
